name: Lintring, Testing, Building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    push: 
        branches: [ master ]
    pull_request: 
        branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest 
    strategy: 
        matrix:
            node-version: [ 20.x ]
    steps:
        - uses: actions/checkout@v2
        - name: Staring Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: install modules
          run: npm install --legacy-peer-deps
        - name: build production project
          run: npm run build:prod
        - name: linting typescript
          run: npm run lint:ts
        - name: linting css
          run: npm run lint:scss
        - name: unit testing
          run: npm run test:unit
        - name: build storybook
          run: npm run storybook:build
        - name: loki update
          run: npx loki update --storiesFilter="^shared\\/Button Primary|shared\\/Button Clear|shared\\/Button Outline|shared\\/Button Outline Dark|widgets\\/LangSwitcher Light|widgets\\/LangSwitcher Dark|widgets\\/PageError Light|widgets\\/PageError Dark|widgets\\/Sidebar Light|widgets\\/Sidebar Dark\$" --reactUri="file:./storybook-static"
        - name: screenshot testing
          run: npm run test:ui:ci
          env: 
            LOKI_CHROME_APP: true